### PR TITLE
Don't chop nonwhitespace when trimming text

### PR DESCRIPTION
**Pull request by peteroupc**
The following patch fixes an issue in which nonwhitespace characters may be chopped if text has a weird indent level, as in the following example:

```
    <summary>
This text may be chopped.
    </summary>
```

I don't know if this happens when XML is compiled but it does happen when the compiled XML is modified afterwards and the XML contains cases like those above.

I haven't been able to test this, in part because notably, Xunit may sandbox assemblies to a temp folder without their XML documentation.

### CODE REVIEW

**Comment by kzu** [comment]
If you could remove the DemoMetro.csproj from the solution, that would probably fix the build error :)

**Comment by peteroupc** [comment]
As you can see, building now fails because XUnit can't find the XML documentation.

**Comment by kzu** [comment]
Add the xml as a content file

**Comment by peteroupc** [comment]
The XML is already a content file.  Again, it seems that XUnit is sandboxing the assemblies to individual folders without their XML documentation or any other content.

**Comment by peteroupc** [comment]
Can you please see this change again?

**Comment by peteroupc** [comment]
It's good to see this project is still "alive".

**Comment by kzu** [comment]
Heya! Yes, I'll revisit all previous PRs once I get the CI back in shape :)

**Comment by kzu** [comment]
Could you reopen against `main` now? A fetch&rebase would be needed since I changed quite a bit of stuff, but mostly formatting and code modernization stuff

**Comment by peteroupc** [comment]
I'm afraid I don't know how to do this in detail, especially since the repository's name and "main" branch name changed in the meantime.

**Pull request closed without merging**
